# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from Timing import Timing
from functions import sleep
import sys
import time
import webbrowser

class Timer(QtCore.QObject):
    finished = QtCore.pyqtSignal()
    progress = QtCore.pyqtSignal(int)
    timing = Timing()
    stop = True

    def setTiming(self, timing: Timing):
        self.timing = timing
        self.stop = False
    
    def hault(self):
        self.stop = True

    def run(self):
        while self.timing.getTimeInSeconds() >= 0:
            if self.stop:
                break
            self.progress.emit(self.timing)
            time.sleep(1)
            self.timing.changeTotalTime(-1)
        self.finished.emit()
        if not self.stop:
            sleep()

class Ui_MainWindow(object):
    running = False
    timing: Timing = Timing()
    
    def openGithub(self):
        webbrowser.open('https://github.com/Mahmoud217TR', new=2)

    def toggleRun(self):
        self.running = not self.running
        _translate = QtCore.QCoreApplication.translate
        if self.running:
            self.submitButton.setText(_translate("MainWindow", "Stop"))
            self.submitButton.setStyleSheet("color:white;\n"
"background-color:red;")
        else:
            self.submitButton.setText(_translate("MainWindow", "Start"))
            self.submitButton.setStyleSheet("color:white;\n"
"background-color:green;")
    
    def getHoursValue(self):
        return int(self.hoursBox.value())
    
    def getMinutesValue(self):
        return int(self.minutesBox.value())
    
    def getSecondsValue(self):
        return int(self.secondsBox.value())
    
    def setHoursValue(self, value:int):
        self.hoursLcd.setProperty("value", value)
    
    def setMinutesValue(self, value:int):
        self.minutesLcd.setProperty("value", value)
    
    def setSecondsValue(self, value:int):
        self.secondsLcd.setProperty("value", value)

    def setBoxesEnabled(self, value: bool = True):
        self.hoursBox.setProperty("enabled", value)
        self.minutesBox.setProperty("enabled", value)
        self.secondsBox.setProperty("enabled", value)

    def updateValues(self, timing):
        self.setSecondsValue(self.timing.getSeconds())
        self.setMinutesValue(self.timing.getMinutes())
        self.setHoursValue(self.timing.getHours())

    def startTimer(self):
        self.timer.setTiming(self.timing)
        self.setBoxesEnabled(False)
        self.thread.start()
            
    def stopTimer(self):
        self.timer.hault()

    def buttonPressed(self):
        if self.running:
            self.stopTimer()
        else:
            self.timing = Timing(self.getSecondsValue(), self.getMinutesValue(), self.getHoursValue())
            self.startTimer()
        self.toggleRun()

    def setupUi(self, MainWindow):
        # Threading
        self.thread = QtCore.QThread()
        self.timer = Timer()

        self.timer.moveToThread(self.thread)

        self.thread.started.connect(self.timer.run)
        self.timer.finished.connect(self.thread.quit)
        # self.timer.finished.connect(self.timer.deleteLater)
        # self.thread.finished.connect(self.thread.deleteLater)
        self.timer.progress.connect(self.updateValues)

        self.thread.finished.connect(
            lambda: self.setBoxesEnabled(True)
        )
        
        # setup UI
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(405, 504)
        MainWindow.setMinimumSize(QtCore.QSize(405, 504))
        MainWindow.setMaximumSize(QtCore.QSize(405, 504))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sleepTimerLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(42)
        self.sleepTimerLabel.setFont(font)
        self.sleepTimerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sleepTimerLabel.setObjectName("sleepTimerLabel")
        self.verticalLayout.addWidget(self.sleepTimerLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hoursLcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.hoursLcd.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hoursLcd.setFont(font)
        self.hoursLcd.setStyleSheet("color:red;")
        self.hoursLcd.setSmallDecimalPoint(False)
        self.hoursLcd.setDigitCount(2)
        self.hoursLcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.hoursLcd.setProperty("value", 0.0)
        self.hoursLcd.setObjectName("hoursLcd")
        self.horizontalLayout_3.addWidget(self.hoursLcd)
        self.lcdSeperator1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lcdSeperator1.setFont(font)
        self.lcdSeperator1.setStyleSheet("color:red;")
        self.lcdSeperator1.setAlignment(QtCore.Qt.AlignCenter)
        self.lcdSeperator1.setObjectName("lcdSeperator1")
        self.horizontalLayout_3.addWidget(self.lcdSeperator1)
        self.minutesLcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.minutesLcd.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.minutesLcd.setFont(font)
        self.minutesLcd.setStyleSheet("color:red;")
        self.minutesLcd.setFrameShape(QtWidgets.QFrame.Box)
        self.minutesLcd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.minutesLcd.setLineWidth(1)
        self.minutesLcd.setSmallDecimalPoint(False)
        self.minutesLcd.setDigitCount(2)
        self.minutesLcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.minutesLcd.setProperty("value", 0.0)
        self.minutesLcd.setObjectName("minutesLcd")
        self.horizontalLayout_3.addWidget(self.minutesLcd)
        self.lcdSeperator2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lcdSeperator2.setFont(font)
        self.lcdSeperator2.setStyleSheet("color:red;")
        self.lcdSeperator2.setAlignment(QtCore.Qt.AlignCenter)
        self.lcdSeperator2.setObjectName("lcdSeperator2")
        self.horizontalLayout_3.addWidget(self.lcdSeperator2)
        self.secondsLcd = QtWidgets.QLCDNumber(self.centralwidget)
        self.secondsLcd.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.secondsLcd.setFont(font)
        self.secondsLcd.setStyleSheet("color:red;")
        self.secondsLcd.setSmallDecimalPoint(False)
        self.secondsLcd.setDigitCount(2)
        self.secondsLcd.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.secondsLcd.setProperty("value", 0.0)
        self.secondsLcd.setObjectName("secondsLcd")
        self.horizontalLayout_3.addWidget(self.secondsLcd)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hoursLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.hoursLabel.setFont(font)
        self.hoursLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hoursLabel.setObjectName("hoursLabel")
        self.horizontalLayout_2.addWidget(self.hoursLabel)
        self.minutesLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.minutesLabel.setFont(font)
        self.minutesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.minutesLabel.setObjectName("minutesLabel")
        self.horizontalLayout_2.addWidget(self.minutesLabel)
        self.secondsLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.secondsLabel.setFont(font)
        self.secondsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.secondsLabel.setObjectName("secondsLabel")
        self.horizontalLayout_2.addWidget(self.secondsLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hoursBox = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hoursBox.setFont(font)
        self.hoursBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hoursBox.setAlignment(QtCore.Qt.AlignCenter)
        self.hoursBox.setMaximum(24)
        self.hoursBox.setObjectName("hoursBox")
        self.horizontalLayout.addWidget(self.hoursBox)
        self.seperator1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.seperator1.setFont(font)
        self.seperator1.setAlignment(QtCore.Qt.AlignCenter)
        self.seperator1.setObjectName("seperator1")
        self.horizontalLayout.addWidget(self.seperator1)
        self.minutesBox = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.minutesBox.setFont(font)
        self.minutesBox.setAlignment(QtCore.Qt.AlignCenter)
        self.minutesBox.setMaximum(59)
        self.minutesBox.setObjectName("minutesBox")
        self.horizontalLayout.addWidget(self.minutesBox)
        self.seperator2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.seperator2.setFont(font)
        self.seperator2.setAlignment(QtCore.Qt.AlignCenter)
        self.seperator2.setObjectName("seperator2")
        self.horizontalLayout.addWidget(self.seperator2)
        self.secondsBox = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.secondsBox.setFont(font)
        self.secondsBox.setAlignment(QtCore.Qt.AlignCenter)
        self.secondsBox.setMaximum(59)
        self.secondsBox.setObjectName("secondsBox")
        self.horizontalLayout.addWidget(self.secondsBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setMinimumSize(QtCore.QSize(100, 99))
        self.submitButton.setMaximumSize(QtCore.QSize(100, 99))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.submitButton.setFont(font)
        self.submitButton.setStyleSheet("color:white;\n"
"background-color:green;")
        self.submitButton.setDefault(False)
        self.submitButton.setObjectName("submitButton")
        self.horizontalLayout_4.addWidget(self.submitButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 405, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGitHub = QtWidgets.QAction(MainWindow)
        self.actionGitHub.setCheckable(False)
        self.actionGitHub.setObjectName("actionGitHub")
        self.menuAbout.addAction(self.actionGitHub)
        self.menubar.addAction(self.menuAbout.menuAction())
        # Actions
        self.submitButton.clicked.connect(self.buttonPressed)
        self.actionGitHub.triggered.connect(self.openGithub)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sleep Timer"))
        self.sleepTimerLabel.setText(_translate("MainWindow", "Sleep Timer"))
        self.lcdSeperator1.setText(_translate("MainWindow", ":"))
        self.lcdSeperator2.setText(_translate("MainWindow", ":"))
        self.hoursLabel.setText(_translate("MainWindow", "Hours"))
        self.minutesLabel.setText(_translate("MainWindow", "Minutes"))
        self.secondsLabel.setText(_translate("MainWindow", "Seconds"))
        self.seperator1.setText(_translate("MainWindow", ":"))
        self.seperator2.setText(_translate("MainWindow", ":"))
        self.submitButton.setText(_translate("MainWindow", "Start"))
        self.menuAbout.setTitle(_translate("MainWindow", "MahmoudTR"))
        self.actionGitHub.setText(_translate("MainWindow", "GitHub"))


def startApp():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    startApp()